blank_issues_enabled: false
contact_links:
  - name: Questions & Discussion
    url: https://github.com/agtm1199/uber-polya/discussions
    about: Ask questions and discuss ideas in GitHub Discussions
